apiVersion: v1
kind: Service
metadata:
    name: okrconversationservice
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: okrconversationservice
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: okrconversationservice
  namespace: unlockokr-api-qa
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  tls:
  - hosts:
    - api-qa.unlockokr.com
    secretName: aks-ingress-tls
  rules:
  - host: api-qa.unlockokr.com
    http:
      paths:
      - path: "/conversation(/|$)(.*)"
        pathType: Prefix
        backend:
          service:
            name: okrconversationservice
            port:
              number: 80